# train.py
import os
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"

import argparse
import json
import random
from typing import Dict, List, Optional

import numpy as np
import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)


SYSTEM_PROMPT = (
    "You are a precise arithmetic assistant. "
    "Given an addition problem, output only the final integer answer. "
    "Ignore any irrelevant text if it appears. "
    "Do not output explanations, steps, punctuation, or extra words."
)


# =========================================================
# Utilities
# =========================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_jsonl(path: str) -> List[Dict]:
    records = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))

    return records


def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0

    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()

    print("=" * 80)
    print("模型参数统计")
    print(f"Trainable params: {trainable_params:,}")
    print(f"All params:       {all_param:,}")
    print(f"Trainable ratio:  {100 * trainable_params / all_param:.4f}%")
    print("=" * 80)


# =========================================================
# Data formatting
# =========================================================

def build_train_text(
    instruction: str,
    input_text: str,
    output: str,
    system: Optional[str] = None,
) -> str:

    sys_prompt = system if system else SYSTEM_PROMPT

    text = (
        f"System: {sys_prompt}\n"
        f"User:\n"
        f"{instruction}\n\n"
        f"{input_text}\n"
        f"Assistant: {output}"
    )

    return text


def convert_records_to_text_dataset(records: List[Dict]) -> Dataset:
    texts = []

    for idx, item in enumerate(records):
        if "instruction" not in item:
            raise KeyError(f"Record {idx} missing field: instruction")
        if "input" not in item:
            raise KeyError(f"Record {idx} missing field: input")
        if "output" not in item:
            raise KeyError(f"Record {idx} missing field: output")

        instruction = item["instruction"]
        input_text = item["input"]
        output = str(item["output"])
        system = item.get("system", None)

        texts.append({
            "text": build_train_text(
                instruction=instruction,
                input_text=input_text,
                output=output,
                system=system,
            )
        })

    return Dataset.from_list(texts)


def tokenize_function(examples, tokenizer, max_length: int):
    outputs = tokenizer(
        examples["text"],
        truncation=True,
        max_length=max_length,
        padding=False,
    )

    return outputs


# =========================================================
# Main
# =========================================================

def main():
    parser = argparse.ArgumentParser(
        description="LoRA fine-tune local LLM on 6-digit addition with Shakespeare distractors"
    )

    # Model / data paths
    parser.add_argument(
        "--base_model",
        type=str,
        default="llama3.2-3b",
        help="Local base model directory.",
    )
    parser.add_argument(
        "--train_file",
        type=str,
        default="data/train_6digit_shakespeare_10000.jsonl",
        help="Training jsonl file generated by generate.py.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="outputs/llama3.2_lora_6digit_shakespeare_10000",
        help="Directory to save LoRA adapter.",
    )

    # Training hyperparameters
    parser.add_argument(
        "--max_length",
        type=int,
        default=512,
        help="Maximum sequence length.",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=4,
        help="Per-device train batch size.",
    )
    parser.add_argument(
        "--grad_accum_steps",
        type=int,
        default=4,
        help="Gradient accumulation steps.",
    )
    parser.add_argument(
        "--num_epochs",
        type=int,
        default=3,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=2e-4,
        help="Learning rate.",
    )
    parser.add_argument(
        "--warmup_ratio",
        type=float,
        default=0.03,
        help="Warmup ratio.",
    )
    parser.add_argument(
        "--weight_decay",
        type=float,
        default=0.0,
        help="Weight decay.",
    )
    parser.add_argument(
        "--logging_steps",
        type=int,
        default=10,
        help="Logging steps.",
    )
    parser.add_argument(
        "--save_steps",
        type=int,
        default=200,
        help="Save steps.",
    )
    parser.add_argument(
        "--save_total_limit",
        type=int,
        default=2,
        help="Maximum number of checkpoints to keep.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed.",
    )

    # LoRA hyperparameters
    parser.add_argument(
        "--lora_r",
        type=int,
        default=16,
    )
    parser.add_argument(
        "--lora_alpha",
        type=int,
        default=32,
    )
    parser.add_argument(
        "--lora_dropout",
        type=float,
        default=0.05,
    )

    # QLoRA option
    parser.add_argument(
        "--use_4bit",
        action="store_true",
        help="Use 4bit QLoRA.",
    )

    # Misc
    parser.add_argument(
        "--gradient_checkpointing",
        action="store_true",
        help="Enable gradient checkpointing.",
    )

    args = parser.parse_args()

    set_seed(args.seed)

    # =====================================================
    # Check paths
    # =====================================================

    if not os.path.isdir(args.base_model):
        raise FileNotFoundError(
            f"no such directory: {args.base_model}"
        )

    if not os.path.isfile(os.path.join(args.base_model, "config.json")):
        raise FileNotFoundError(
            f"{args.base_model} is not a valid Hugging Face model directory (missing config.json)"
        )

    if not os.path.isfile(args.train_file):
        raise FileNotFoundError(
            f"no such file: {args.train_file}"
        )

    os.makedirs(args.output_dir, exist_ok=True)

    print("=" * 80)
    print("training configuration")
    print(f"Base model:              {args.base_model}")
    print(f"Train file:              {args.train_file}")
    print(f"Output dir:              {args.output_dir}")
    print(f"Max length:              {args.max_length}")
    print(f"Batch size:              {args.batch_size}")
    print(f"Gradient accumulation:   {args.grad_accum_steps}")
    print(f"Epochs:                  {args.num_epochs}")
    print(f"Learning rate:           {args.learning_rate}")
    print(f"Use 4bit:                {args.use_4bit}")
    print(f"Gradient checkpointing:  {args.gradient_checkpointing}")
    print("=" * 80)

    # =====================================================
    # Load tokenizer
    # =====================================================

    print("start loading tokenizer")

    tokenizer = AutoTokenizer.from_pretrained(
        args.base_model,
        use_fast=True,
        local_files_only=True,
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    tokenizer.padding_side = "right"

    # =====================================================
    # Load model
    # =====================================================

    print("start loading model")

    torch_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

    quantization_config = None

    if args.use_4bit:
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
        )

        model = AutoModelForCausalLM.from_pretrained(
            args.base_model,
            local_files_only=True,
            quantization_config=quantization_config,
            torch_dtype=torch.bfloat16,
            low_cpu_mem_usage=True,
            device_map="auto",
        )

    else:
        model = AutoModelForCausalLM.from_pretrained(
            args.base_model,
            local_files_only=True,
            torch_dtype=torch_dtype,
            low_cpu_mem_usage=True,
        )

        if torch.cuda.is_available():
            model = model.to("cuda")

    model.config.use_cache = False

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()

    if args.use_4bit:
        model = prepare_model_for_kbit_training(model)

    # =====================================================
    # LoRA
    # =====================================================

    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
    )

    model = get_peft_model(model, lora_config)
    print_trainable_parameters(model)

    # =====================================================
    # Load and tokenize dataset
    # =====================================================

    print("=" * 80)
    print("读取训练数据")
    print("=" * 80)

    train_records = load_jsonl(args.train_file)
    train_dataset = convert_records_to_text_dataset(train_records)

    print(f"Number of training examples: {len(train_dataset)}")
    print("=" * 80)
    print("training data example")
    print(train_dataset[0]["text"])
    print("=" * 80)

    tokenized_train_dataset = train_dataset.map(
        lambda x: tokenize_function(x, tokenizer, args.max_length),
        batched=True,
        remove_columns=train_dataset.column_names,
        desc="Tokenizing train dataset",
    )

    data_collator = DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    )

    # =====================================================
    # Training args
    # =====================================================

    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.num_epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum_steps,
        learning_rate=args.learning_rate,
        warmup_ratio=args.warmup_ratio,
        weight_decay=args.weight_decay,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        bf16=torch.cuda.is_available(),
        fp16=False,
        report_to="none",
        remove_unused_columns=False,
        dataloader_pin_memory=False,
        seed=args.seed,
        gradient_checkpointing=args.gradient_checkpointing,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # =====================================================
    # Train
    # =====================================================

    print("=" * 80)
    print("start training")
    print("=" * 80)

    trainer.train()

    # =====================================================
    # Save
    # =====================================================

    print("=" * 80)
    print("save LoRA adapter")
    print("=" * 80)

    model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)

    print("=" * 80)
    print("training completed")
    print(f"LoRA adapter saved to: {args.output_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()
